feat: navigate to submissions page when clicked on the file icon in qr popup
hotosm/fmtm pull request #1300
Opened 2024-02-29 05:03 UTC by Prajwalism

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Issue

Fixes #1243 

## Describe this PR

This PR enables us to navigate to the submissions page when clicked on the `QR-popup` file icon with the `taskId` filter on.

## Screenshots

Please provide screenshots of the change.

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the FMTM Code of Conduct: <https://github.com/hotosm/fmtm/blob/main/CODE_OF_CONDUCT.md>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-29 07:28 UTC, varun2948 approved these changes

2024-02-29 12:08 UTC, spwoodcock commented on src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx
> +            navigate(`/project-submissions/MTAwMTExMTE=?tab=table&task_id=${taskId}`);
Is this navigating to a hardcoded project url?
Shouldn't it be dynamic based on the current project page, or am I missing something?

2024-03-01 16:44 UTC, spwoodcock commented
Looks like a merge got bodged somewhere 😄 
I would either:
- Copy your changes out somewhere, reset this branch, then copy them back in and force push.
- Rebase this branch with `development`:

```bash
git checkout development
git pull
git checkout feat/qr-popup-icons
git rebase development
```

2024-03-01 16:52 UTC, Prajwalism commented
@spwoodcock sorry for the mistake, I will proceed to do as you mentioned.

2024-03-04 17:17 UTC, spwoodcock commented
This looks good, but still includes commits from other PRs somehow.
E.g. https://github.com/hotosm/fmtm/pull/1300/commits/9cacda17e4f3ff6413c2c6ad13821fdb87aa37cc

Feel free to copy the code across to another PR if it helps 😄

2024-03-04 17:17 UTC, spwoodcock requested changes
see comment

2024-03-07 06:50 UTC, NSUWAL123 commented
@spwoodcock , I am closing this PR. I will make changes and push in another PR.

2024-03-07 06:50 UTC, closed without merging