Feat/login options
hotosm/fmtm pull request #1458
Opened 2024-04-18 10:10 UTC by NSUWAL123

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue
- Related to #1438

## Describe this PR
This PR adds a functionality where on sign-in button click a popup is displayed where user will able to choose between OSM login or Temporary login.

## Screenshots
![image](https://github.com/hotosm/fmtm/assets/81785002/3bfa41a3-fea5-4f07-852d-0cf72e61163f)

## Alternative Approaches Considered

Did you attempt any other approaches that are not documented in code?

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the FMTM Contributing Guide: <https://github.com/hotosm/fmtm/blob/main/CONTRIBUTING.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.

## [optional] What gif best describes this PR or how it makes you feel?

2024-04-18 16:11 UTC, spwoodcock requested changes
Very clean, looks great!

2024-04-18 16:11 UTC, spwoodcock commented on src/frontend/src/assets/images/osm-logo.png
![osm-logo](https://github.com/hotosm/fmtm/assets/78538841/81669831-6812-4163-aeeb-f616d14c05ef)

The logo is a big large for what we need, at 64kb or so.
Could we use the one attached, 64px x 64px and only 9kb?

2024-04-18 16:18 UTC, spwoodcock commented
I assume the user is displayed as `svcfmtm` (or whatever service account was set up) after temporary login.
Could we possibly override this to always display as `Temporary`?

I know it's not super simple, as it probably also requires another state param to determine that the user logged in via temp auth, but it's a nicer user experience!

The temp login cookie (containing the token) lasts for 7 days.
The code in https://github.com/hotosm/fmtm/pull/1462 will detect if the cookie is no longer valid or present, and log the user out on the frontend automatically (clearing the login state).

2024-04-19 03:33 UTC, NSUWAL123 commented
@spwoodcock, currently when logged in with temporary account `local admin` is shown in the username. You mean to say that if a user is logging in from the temporary account, in the frontend we shall display username as `Temporary` instead of `local admin`?

2024-04-19 08:20 UTC, spwoodcock commented
local admin is actually an override only used during development!

Comment out `DEBUG=true` in your .env file and run `docker compose up -d` to see what I mean. 

The related PR that I linked will change that behaviour. Maybe we should merge that first, then rebase this for testing before merge

2024-04-19 08:22 UTC, spwoodcock commented
I just merged #1462 👍

2024-04-23 12:26 UTC, spwoodcock approved these changes
Looks good 👍 

It's easier for me to merge this on continue to work on it.

We might need a little tweak to make the `/auth/introspect` call on first page load play nicely with the temp auth/login.

2024-04-23 12:26 UTC, merged