feat: auto unlock locked tasks after 3 days
hotosm/fmtm pull request #1984
Opened 2024-12-12 07:49 UTC by Anuj-Gupta4

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation
- [ ] 🧑‍💻 Refactor
- [ ] ✅ Test
- [ ] 🤖 Build or CI
- [ ] ❓ Other (please specify)

## Related Issue

- Resolves #1603 

## Describe this PR

A new function has been created here that will unlock stale tasks.
There is also an endpoint that will help us test it manually.

## Review Guide

Is there a better way to do this without disabling `task_event_state_trigger`?
Is the logic implemented here correct?

2024-12-16 17:56 UTC, spwoodcock commented
Sorry for taking so long to review!

Good thinking also accounting for the entities / building unlock, as well as tasks.

Is there any chance we could look into:

- Only do this for projects with activity in the last week. While we run the cron at a schedule, we should first filter down so we only run the logic on projects with recent activity (did determined from task_events entries is good enough). Of activity, continue to the unlocking logic.

- Using the updatedAt field that already exists in ODK for entities. I'm not sure we need a new field in our db. I think the ODK entites unlocking can be done via the process:
  1. Call the sync function to sync current status from ODK
  2. If there are any entities that are status 1 (open in ODK), we continue to the unlocking logic.
  3. If we call the ODK API to get entity data, including the updatedAt field (hopefully we can reuse existing functions just using different odata filters, but might need to modify slightly?). Using odata filters we should be able to get entities with updates over 1 day ago, also via the updatedAt field.

The criteria for unlocking can be found in this comment:

2024-12-17 07:25 UTC, Anuj-Gupta4 commented
@spwoodcock
Both the sync api and osm fieldwork's getentitydata functions work on a single project at a time.
We would have to write some logic to get active projects and then sync data for each project in a loop.
If it is alright to do this, then there should be no other issues with this solution.

2024-12-17 09:30 UTC, spwoodcock commented
Yeah I think its OK!

This cron probably won't run really frequently, plus perhaps we can optimise in future somehow.

But I imagine there will only be at most 10-20 active projects in the last week at any one time.

Calling the ODK Central API for each is the only way unfortunately, due to the constraint of needing to support external ODK Collect instances

2024-12-18 16:37 UTC, spwoodcock commented
Apologies I won't get time to review this for a while @Anuj-Gupta4 🙏 

It's a very nice chance, but it's low priority for now & I'm really running against the clock!

If you could do some thorough testing in different scenarios, it will really help the review/merge in the new year ⭐

2024-12-19 07:20 UTC, Anuj-Gupta4 commented
No worries!
We can come back to this later if it is more convenient.

2025-01-30 23:12 UTC, spwoodcock approved these changes

2025-01-30 23:13 UTC, spwoodcock requested changes
Nice PR, especially the SQL! I accidentally aporoved in instead of requesting a few small changes. Comments are in previous review

2025-01-30 23:22 UTC, spwoodcock commented on src/backend/app/tasks/task_routes.py
> +            'UNLOCKED_TO_MAP'::mappingstate,
I see what you did there now: disable the trigger, insert, then re-enable. I'm not sure about doing that 😅

Do you think we should add a new event, perhaps 'RESET', that is used to set the state back to 'UNLOCKED_TO_MAP'?

I can't see any downside of doing that currently - although I am on my phone and might have missed something though!

2025-02-05 07:11 UTC, Anuj-Gupta4 commented on src/backend/app/tasks/task_routes.py
> +            'UNLOCKED_TO_MAP'::mappingstate,
I too wasn't sure about the trigger part. Adding a new task event works well. 👍

2025-02-05 09:01 UTC, spwoodcock requested changes

2025-02-05 09:01 UTC, spwoodcock commented on src/backend/migrations/008-add-taskevent-enumtype.sql
> +        WHEN 'RESET' THEN
Good idea adding this 👍

But any updates made in migrations need to replicated in the init SQL script for a new FMTM instance that is set up 😄

2025-02-05 09:02 UTC, spwoodcock commented
> The tests are passing locally.

This only adds stuff, so doesn't affect tests. I think it was just an issue on the commit this is based on, so noboriblem when merged into current dev

2025-02-05 09:17 UTC, Anuj-Gupta4 commented on src/backend/migrations/008-add-taskevent-enumtype.sql
> +        WHEN 'RESET' THEN
I is already present in fmtm_base_schema.sql file as well.

2025-02-05 12:02 UTC, spwoodcock approved these changes

2025-02-05 12:03 UTC, merged