changed single polygon to merged polygon POI if uploaded multi polygon during project area edit
hotosm/fmtm pull request #829
Opened 2023-09-12 08:32 UTC by Sujanadh

2023-09-13 06:18 UTC, nrjadkry approved these changes

2023-09-14 08:55 UTC, nrjadkry requested changes

2023-09-14 08:55 UTC, nrjadkry commented on src/backend/app/projects/project_crud.py
> -    try:
@Sujanadh You have commented the try except block

2023-09-25 06:48 UTC, nrjadkry approved these changes

2023-09-25 06:49 UTC, nrjadkry commented
@spwoodcock Have you looked into this PR. Looks good to me.

2023-09-25 06:52 UTC, spwoodcock approved these changes

2023-09-25 06:52 UTC, spwoodcock commented
Thanks for the prompt Niraj! Hectic few weeks 😄

2023-09-25 06:53 UTC, merged

2023-09-25 06:55 UTC, spwoodcock commented
And of course, thank you @Sujanadh for the PR!